name: Terraform CI

on:
  push:
    branches:
      - main  # Ye workflow main branch pe push hone par chalega

jobs:
  terraform:
    runs-on: ubuntu-latest  # Ubuntu pe run hoga

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # GitHub repo ko checkout karna

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3  # Terraform setup karna

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2  # AWS credentials set karna
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Write tfvars from secret
      run: |
        echo "${{ secrets.TF_VARS }}" > terraform.auto.tfvars  # Secret ko terraform.auto.tfvars file me likhna

    - name: Terraform Init
      run: terraform init  # Terraform ko initialize karna

    - name: Terraform Validate
      run: terraform validate  # Terraform configuration ko validate karna

    - name: Terraform Plan
      run: terraform plan  # Terraform plan generate karna

    - name: Terraform Apply
      run: terraform apply -auto-approve  # Terraform apply karna
