name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./main

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Show TF_VARS content (for debugging)
      run: echo "${{ secrets.TF_VARS }}"

    - name: Write tfvars from secret
      run: |
        echo "${{ secrets.TF_VARS }}" > terraform.auto.tfvars

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
